# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/onboarding/v1/onboarding.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from protobuf.type.v1 import banking_pb2 as protobuf_dot_type_dot_v1_dot_banking__pb2
from protobuf.type.v1 import pix_pb2 as protobuf_dot_type_dot_v1_dot_pix__pb2
from protobuf.type.v1 import registration_pb2 as protobuf_dot_type_dot_v1_dot_registration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'protobuf/onboarding/v1/onboarding.proto\x12\x16protobuf.onboarding.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1eprotobuf/type/v1/banking.proto\x1a\x1aprotobuf/type/v1/pix.proto\x1a#protobuf/type/v1/registration.proto\"\x94\x01\n\nOnboarding\x12N\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32*.protobuf.onboarding.v1.OnboardingCustomerB\x06\xbaH\x03\xc8\x01\x01R\x08\x63ustomer\x12\x36\n\nextra_data\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructR\textraData\"\xa8\x02\n\x12OnboardingCustomer\x12\x17\n\x02id\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x02id\x12O\n\x11registration_data\x18\x02 \x01(\x0b\x32\".protobuf.type.v1.RegistrationDataR\x10registrationData\x12@\n\x0c\x62\x61nking_data\x18\x03 \x01(\x0b\x32\x1d.protobuf.type.v1.BankingDataR\x0b\x62\x61nkingData\x12\x17\n\x07pix_key\x18\x04 \x03(\tR\x06pixKey\x12M\n\x0cpix_key_type\x18\x05 \x03(\x0e\x32\x1c.protobuf.type.v1.PixKeyTypeB\r\xbaH\n\x92\x01\x07\"\x05\x82\x01\x02\x10\x01R\npixKeyTypeBVZTgithub.com/vinirmbrozz/protobuf-contracts/gen/go/protobuf/onboarding/v1;onboardingv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.onboarding.v1.onboarding_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZTgithub.com/vinirmbrozz/protobuf-contracts/gen/go/protobuf/onboarding/v1;onboardingv1'
  _ONBOARDING.fields_by_name['customer']._options = None
  _ONBOARDING.fields_by_name['customer']._serialized_options = b'\272H\003\310\001\001'
  _ONBOARDINGCUSTOMER.fields_by_name['id']._options = None
  _ONBOARDINGCUSTOMER.fields_by_name['id']._serialized_options = b'\272H\004r\002\020\001'
  _ONBOARDINGCUSTOMER.fields_by_name['pix_key_type']._options = None
  _ONBOARDINGCUSTOMER.fields_by_name['pix_key_type']._serialized_options = b'\272H\n\222\001\007\"\005\202\001\002\020\001'
  _ONBOARDING._serialized_start=224
  _ONBOARDING._serialized_end=372
  _ONBOARDINGCUSTOMER._serialized_start=375
  _ONBOARDINGCUSTOMER._serialized_end=671
# @@protoc_insertion_point(module_scope)
