# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/type/v1/address.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eprotobuf/type/v1/address.proto\x12\x10protobuf.type.v1\"\xce\x01\n\x07\x41\x64\x64ress\x12\x19\n\x08zip_code\x18\x01 \x01(\tR\x07zipCode\x12\x12\n\x04\x63ity\x18\x02 \x01(\tR\x04\x63ity\x12\x1f\n\x0bstreet_name\x18\x03 \x01(\tR\nstreetName\x12#\n\rstreet_number\x18\x04 \x01(\tR\x0cstreetNumber\x12\x1e\n\ncomplement\x18\x05 \x01(\tR\ncomplement\x12\x14\n\x05state\x18\x06 \x01(\tR\x05state\x12\x18\n\x07\x63ountry\x18\x07 \x01(\tR\x07\x63ountryBJZHgithub.com/vinirmbrozz/protobuf-contracts/gen/go/protobuf/type/v1;typev1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.type.v1.address_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZHgithub.com/vinirmbrozz/protobuf-contracts/gen/go/protobuf/type/v1;typev1'
  _ADDRESS._serialized_start=53
  _ADDRESS._serialized_end=259
# @@protoc_insertion_point(module_scope)
