# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/type/v1/banking.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eprotobuf/type/v1/banking.proto\x12\x10protobuf.type.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x03\n\x0b\x42\x61nkingData\x12!\n\x0c\x61\x63\x63ount_type\x18\x01 \x01(\tR\x0b\x61\x63\x63ountType\x12)\n\x10institution_name\x18\x02 \x01(\tR\x0finstitutionName\x12\x1b\n\tbank_code\x18\x03 \x01(\tR\x08\x62\x61nkCode\x12\x1f\n\x0b\x62ranch_code\x18\x04 \x01(\tR\nbranchCode\x12\x1f\n\x0b\x62ranch_name\x18\x05 \x01(\tR\nbranchName\x12\x1d\n\naccount_id\x18\x06 \x01(\tR\taccountId\x12\x18\n\x07\x63ountry\x18\x07 \x01(\tR\x07\x63ountry\x12J\n\x13\x61\x63\x63ount_create_date\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x11\x61\x63\x63ountCreateDate\x12S\n\x18\x61\x63\x63ount_last_update_date\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x15\x61\x63\x63ountLastUpdateDateBJZHgithub.com/vinirmbrozz/protobuf-contracts/gen/go/protobuf/type/v1;typev1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.type.v1.banking_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZHgithub.com/vinirmbrozz/protobuf-contracts/gen/go/protobuf/type/v1;typev1'
  _BANKINGDATA._serialized_start=86
  _BANKINGDATA._serialized_end=490
# @@protoc_insertion_point(module_scope)
