# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/type/v1/registration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from protobuf.type.v1 import address_pb2 as protobuf_dot_type_dot_v1_dot_address__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#protobuf/type/v1/registration.proto\x12\x10protobuf.type.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eprotobuf/type/v1/address.proto\"\xb3\x02\n\x10RegistrationData\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mail\x12R\n\x17\x64\x61tetime_account_create\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x15\x64\x61tetimeAccountCreate\x12!\n\x0cphone_number\x18\x04 \x01(\tR\x0bphoneNumber\x12\x1c\n\tbirthdate\x18\x05 \x01(\tR\tbirthdate\x12\x19\n\x08\x64oc_type\x18\x06 \x01(\tR\x07\x64ocType\x12\x10\n\x03\x64oc\x18\x07 \x01(\tR\x03\x64oc\x12\x33\n\x07\x61\x64\x64ress\x18\x08 \x01(\x0b\x32\x19.protobuf.type.v1.AddressR\x07\x61\x64\x64ressBJZHgithub.com/vinirmbrozz/protobuf-contracts/gen/go/protobuf/type/v1;typev1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.type.v1.registration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZHgithub.com/vinirmbrozz/protobuf-contracts/gen/go/protobuf/type/v1;typev1'
  _REGISTRATIONDATA._serialized_start=123
  _REGISTRATIONDATA._serialized_end=430
# @@protoc_insertion_point(module_scope)
