# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/type/v1/pix.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotobuf/type/v1/pix.proto\x12\x10protobuf.type.v1*\xa0\x01\n\nPixKeyType\x12\x1c\n\x18PIX_KEY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10PIX_KEY_TYPE_CPF\x10\x01\x12\x15\n\x11PIX_KEY_TYPE_CNPJ\x10\x02\x12\x16\n\x12PIX_KEY_TYPE_EMAIL\x10\x03\x12\x16\n\x12PIX_KEY_TYPE_PHONE\x10\x04\x12\x17\n\x13PIX_KEY_TYPE_RANDOM\x10\x05\x42JZHgithub.com/vinirmbrozz/protobuf-contracts/gen/go/protobuf/type/v1;typev1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.type.v1.pix_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZHgithub.com/vinirmbrozz/protobuf-contracts/gen/go/protobuf/type/v1;typev1'
  _PIXKEYTYPE._serialized_start=49
  _PIXKEYTYPE._serialized_end=209
# @@protoc_insertion_point(module_scope)
