# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/transaction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/transaction.proto\x12\x13truther.transaction\"\xf8\x01\n\x12PredictiveAnalyzer\x12\x1c\n\tisAllowed\x18\x01 \x01(\x08R\tisAllowed\x12\x16\n\x06reason\x18\x02 \x01(\tR\x06reason\x12\x16\n\x06\x63\x61rdId\x18\x03 \x01(\tR\x06\x63\x61rdId\x12\x16\n\x06userId\x18\x04 \x01(\tR\x06userId\x12$\n\rwalletAddress\x18\x05 \x01(\tR\rwalletAddress\x12\x1c\n\tallowance\x18\x06 \x01(\tR\tallowance\x12$\n\rtransactionId\x18\x07 \x01(\tR\rtransactionId\x12\x12\n\x04name\x18\x08 \x01(\tR\x04name\"\xbb\x01\n\x0bTransaction\x12,\n\x11transactionAmount\x18\x01 \x01(\tR\x11transactionAmount\x12W\n\x12predictiveAnalyzer\x18\x02 \x01(\x0b\x32\'.truther.transaction.PredictiveAnalyzerR\x12predictiveAnalyzer\x12%\n\x0e\x66inal_decision\x18\x03 \x01(\tR\rfinalDecisionB=Z;github.com/vinirmbrozz/truther-contracts/gen/go/transactionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.transaction_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z;github.com/vinirmbrozz/truther-contracts/gen/go/transaction'
  _PREDICTIVEANALYZER._serialized_start=49
  _PREDICTIVEANALYZER._serialized_end=297
  _TRANSACTION._serialized_start=300
  _TRANSACTION._serialized_end=487
# @@protoc_insertion_point(module_scope)
