// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: protobuf/type/v1/pix.proto

package typev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PixKeyType — valid Pix key types. DataRudder validated the raw string against
// this set (CPF, CNPJ, EMAIL, PHONE, RANDOM).
type PixKeyType int32

const (
	PixKeyType_PIX_KEY_TYPE_UNSPECIFIED PixKeyType = 0
	PixKeyType_PIX_KEY_TYPE_CPF         PixKeyType = 1
	PixKeyType_PIX_KEY_TYPE_CNPJ        PixKeyType = 2
	PixKeyType_PIX_KEY_TYPE_EMAIL       PixKeyType = 3
	PixKeyType_PIX_KEY_TYPE_PHONE       PixKeyType = 4
	PixKeyType_PIX_KEY_TYPE_RANDOM      PixKeyType = 5
)

// Enum value maps for PixKeyType.
var (
	PixKeyType_name = map[int32]string{
		0: "PIX_KEY_TYPE_UNSPECIFIED",
		1: "PIX_KEY_TYPE_CPF",
		2: "PIX_KEY_TYPE_CNPJ",
		3: "PIX_KEY_TYPE_EMAIL",
		4: "PIX_KEY_TYPE_PHONE",
		5: "PIX_KEY_TYPE_RANDOM",
	}
	PixKeyType_value = map[string]int32{
		"PIX_KEY_TYPE_UNSPECIFIED": 0,
		"PIX_KEY_TYPE_CPF":         1,
		"PIX_KEY_TYPE_CNPJ":        2,
		"PIX_KEY_TYPE_EMAIL":       3,
		"PIX_KEY_TYPE_PHONE":       4,
		"PIX_KEY_TYPE_RANDOM":      5,
	}
)

func (x PixKeyType) Enum() *PixKeyType {
	p := new(PixKeyType)
	*p = x
	return p
}

func (x PixKeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PixKeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_type_v1_pix_proto_enumTypes[0].Descriptor()
}

func (PixKeyType) Type() protoreflect.EnumType {
	return &file_protobuf_type_v1_pix_proto_enumTypes[0]
}

func (x PixKeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PixKeyType.Descriptor instead.
func (PixKeyType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_type_v1_pix_proto_rawDescGZIP(), []int{0}
}

var File_protobuf_type_v1_pix_proto protoreflect.FileDescriptor

var file_protobuf_type_v1_pix_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2a, 0xa0,
	0x01, 0x0a, 0x0a, 0x50, 0x69, 0x78, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x18, 0x50, 0x49, 0x58, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50,
	0x49, 0x58, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x50, 0x46, 0x10,
	0x01, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x49, 0x58, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x43, 0x4e, 0x50, 0x4a, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x49, 0x58, 0x5f,
	0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x03,
	0x12, 0x16, 0x0a, 0x12, 0x50, 0x49, 0x58, 0x5f, 0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x49, 0x58, 0x5f,
	0x4b, 0x45, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x10,
	0x05, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x76, 0x69, 0x6e, 0x69, 0x72, 0x6d, 0x62, 0x72, 0x6f, 0x7a, 0x7a, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x67,
	0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_type_v1_pix_proto_rawDescOnce sync.Once
	file_protobuf_type_v1_pix_proto_rawDescData = file_protobuf_type_v1_pix_proto_rawDesc
)

func file_protobuf_type_v1_pix_proto_rawDescGZIP() []byte {
	file_protobuf_type_v1_pix_proto_rawDescOnce.Do(func() {
		file_protobuf_type_v1_pix_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_type_v1_pix_proto_rawDescData)
	})
	return file_protobuf_type_v1_pix_proto_rawDescData
}

var file_protobuf_type_v1_pix_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_type_v1_pix_proto_goTypes = []interface{}{
	(PixKeyType)(0), // 0: protobuf.type.v1.PixKeyType
}
var file_protobuf_type_v1_pix_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_type_v1_pix_proto_init() }
func file_protobuf_type_v1_pix_proto_init() {
	if File_protobuf_type_v1_pix_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_type_v1_pix_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_type_v1_pix_proto_goTypes,
		DependencyIndexes: file_protobuf_type_v1_pix_proto_depIdxs,
		EnumInfos:         file_protobuf_type_v1_pix_proto_enumTypes,
	}.Build()
	File_protobuf_type_v1_pix_proto = out.File
	file_protobuf_type_v1_pix_proto_rawDesc = nil
	file_protobuf_type_v1_pix_proto_goTypes = nil
	file_protobuf_type_v1_pix_proto_depIdxs = nil
}
